/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as authenticatedIndexRouteImport } from './routes/(authenticated)/index'
import { Route as publicRegisterRouteImport } from './routes/(public)/register'
import { Route as publicSignInIndexRouteImport } from './routes/(public)/sign-in.index'
import { Route as authenticatedProjectsIndexRouteImport } from './routes/(authenticated)/projects.index'

const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedIndexRoute = authenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const publicRegisterRoute = publicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicSignInIndexRoute = publicSignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => publicRouteRoute,
} as any)
const authenticatedProjectsIndexRoute =
  authenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/register': typeof publicRegisterRoute
  '/': typeof authenticatedIndexRoute
  '/projects/': typeof authenticatedProjectsIndexRoute
  '/sign-in/': typeof publicSignInIndexRoute
}
export interface FileRoutesByTo {
  '/register': typeof publicRegisterRoute
  '/': typeof authenticatedIndexRoute
  '/projects': typeof authenticatedProjectsIndexRoute
  '/sign-in': typeof publicSignInIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/(public)': typeof publicRouteRouteWithChildren
  '/(public)/register': typeof publicRegisterRoute
  '/(authenticated)/': typeof authenticatedIndexRoute
  '/(authenticated)/projects/': typeof authenticatedProjectsIndexRoute
  '/(public)/sign-in/': typeof publicSignInIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/register' | '/' | '/projects/' | '/sign-in/'
  fileRoutesByTo: FileRoutesByTo
  to: '/register' | '/' | '/projects' | '/sign-in'
  id:
    | '__root__'
    | '/(authenticated)'
    | '/(public)'
    | '/(public)/register'
    | '/(authenticated)/'
    | '/(authenticated)/projects/'
    | '/(public)/sign-in/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  publicRouteRoute: typeof publicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/': {
      id: '/(authenticated)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authenticatedIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(public)/register': {
      id: '/(public)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof publicRegisterRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/sign-in/': {
      id: '/(public)/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof publicSignInIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(authenticated)/projects/': {
      id: '/(authenticated)/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof authenticatedProjectsIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
  }
}

interface authenticatedRouteRouteChildren {
  authenticatedIndexRoute: typeof authenticatedIndexRoute
  authenticatedProjectsIndexRoute: typeof authenticatedProjectsIndexRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedIndexRoute: authenticatedIndexRoute,
  authenticatedProjectsIndexRoute: authenticatedProjectsIndexRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

interface publicRouteRouteChildren {
  publicRegisterRoute: typeof publicRegisterRoute
  publicSignInIndexRoute: typeof publicSignInIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicRegisterRoute: publicRegisterRoute,
  publicSignInIndexRoute: publicSignInIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
